name: Deploy to Azure VM
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build . --platform linux/amd64 -t comp7940bot
          docker save -o comp7940bot.tar comp7940bot:latest

      - name: Transfer code to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          source: "."
          target: "~/comp7940bot"
          strip_components: 1

      - name: Build and Run image on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          script: |
            cd ~/comp7940bot
            
            # Stop old container
            docker stop comp7940bot || true
            docker rm comp7940bot || true
            
            docker build . --platform linux/amd64 -t comp7940bot
            
            docker run -d \
              --name comp7940bot \
              --restart unless-stopped \
              comp7940bot:latest
            